#!/bin/bash

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Learn $BORG_REPO
source /etc/borg-helper/borg-helper.conf

# Init borg repository
borg init \
    --remote-path=borg1 \
    --encryption=keyfile-blake2
